name: 'Deploy - Terraform'
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, '[deploy]')"
    defaults:
      run:
        shell: bash
    env:
      DATA_DIR: ./data
      DOCKER_USER: 1100
      DO_PAT: ${{ secrets.DO_PAT }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
    - uses: actions/checkout@v2

    - name: Install ssh key
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIVATE_KEY" > ~/.ssh/terraform
        chmod 600 ~/.ssh/terraform
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
        
    - name: Initialize Terraform
      run: terraform init

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_PAT }}
      
    - name: Terraform Plan
      run: ./pelias terraform plan

    - name: Terraform Apply
      if: >-
        github.ref == 'refs/heads/master' && 
        github.event_name == 'push'
      run: ./pelias terraform apply
