name: 'Deploy - Terraform - Feature Branch'
on: 
  push:
    branches-ignore:
      - main
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    env:
      DATA_DIR: ./data
      DOCKER_USER: 1100
      DO_PAT: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
    - uses: actions/checkout@v2
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Install ssh key
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIVATE_KEY" > ~/.ssh/terraform
        chmod 600 ~/.ssh/terraform

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.1
        
    - name: Initialize Terraform
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: ./pelias terraform plan

    - name: Terraform Apply
      run: ./pelias terraform apply
