name: CI & CD ?

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2

    - name: Install CLI tool
      shell: bash
      run: |
        echo export PATH=$PATH:`pwd`/pelias >> ~/.bash_profile
        source ~/.bash_profile
        sudo ln -s `pwd`/pelias /usr/local/bin
        
    - name: create the data directory
      run: |
        mkdir -p data/elasticsearch
        sudo chown 1000:1000 -R data/elasticsearch
        ls -n data
        ls -n data/elasticsearch
        
    - name: Bring up Elasticsearch and Create Index
      shell: bash
      run: |
        export DATA_DIR=$(pwd)/data
        pelias compose up elasticsearch
        pelias elastic wait
        
