name: CI & CD ?

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ELASTIC_HOST: localhost
    steps:
      - name: who am i?
        run: whoami
      - name: set up user
        run: |
          sudo useradd --create-home -p $( echo pelias | openssl passwd -1 -stdin ) -u 1100 pelias
          sudo usermod -aG docker pelias
          sudo usermod -aG sudo pelias
          sudo usermod --shell /bin/bash pelias
          sudo su - pelias

          git clone https://github.com/NYCPlanning/labs-geosearch-docker.git geosearch

          cd geosearch
          mkdir -p data/elasticsearch

          echo "Bringing up elasticsearch..."
          ./pelias compose up elasticsearch

          echo "Bringing up libpostal, and api..."
          ./pelias compose up api libpostal

          echo "All done!"
          
      - name: create
        working-directory: geosearch
        run: |
          ./pelias elastic status
          docker ps 
          docker logs pelias_elasticsearch
          
          ./pelias elastic wait
          ./pelias elastic create
      
      - name: import pad
        working-directory: geosearch
        run: ./pelias import nycpad
        
