name: CI & CD ?

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ELASTIC_HOST: localhost
    steps:
      - name: who am i?
        run: whoami
      - name: set up user
        run: |
          sudo useradd --create-home -p $( echo pelias | openssl passwd -1 -stdin ) -u 1100 pelias
          sudo usermod -aG docker pelias
          sudo usermod -aG sudo pelias
          sudo usermod --shell /bin/bash pelias
          sudo su - pelias

          whoami 
          
          git clone https://github.com/NYCPlanning/labs-geosearch-docker.git geosearch

          cd geosearch
          mkdir -p data/elasticsearch

          ./pelias compose up elasticsearch
          
      - name: create
        working-directory: geosearch
        run: |
          ls -l data
          ls -l data/elasticsearch
        
