name: GeoSearch Deployment testing

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
      
    - name: setup server
      run: |
        bash setupServer.sh
        
    - name: setup geosearch
      run: |
        bash setupGeosearch.sh
    
    - name: check if everything is working
      run: |
        docker ps
        
        curl localhost:4400/expand?address=120%20Broadway%20NY%20NY | jq '.'
        
        curl -s localhost:4000/status
        
        curl localhost:4000/v1/autocomplete?text=1415%20ave%20w | jq 'keys'
